FROM ethereum/client-go
ADD ./genesis.json /usr/local/bin/genesis.json

WORKDIR /usr/local/bin/

ENV minerAddress=""
ARG privateKey
ARG password

ENV bootnodeId=""
ENV bootnodeIp=""
RUN echo $privateKey > privateKey & echo $password > password & geth account import --password ./password ./privateKey
RUN geth init genesis.json
ENTRYPOINT ["/bin/sh"]
CMD ["-c", "/usr/local/bin/geth --networkid \"45\" --bootnodes \"enode://${bootnodeId}@${bootnodeIp}:30301\" --mine --minerthreads=2 --syncmode=full --etherbase ${minerAddress} --unlock ${minerAddress} --password /usr/local/bin/password"]